<a href="https://colab.research.google.com/github/Sumanth1242/MKsumanth_data690/blob/main/Assignment_05/Assignment_05_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np
import warnings

# Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])


array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([0, .5, 1, 1.5, 2])

In [7]:
a[3], a[1]


(4, 2)

In [6]:
b[[0, 3, -1]]

array([0. , 1.5, 2. ])

# Dimensions and shapes

In [11]:
A = np.array([
    [2, 4, 0],
    [8, 1, 7]
])

In [9]:
A.shape

(2, 3)

In [10]:
A.size

6

In [14]:
c = np.array([
    [
        [2, 1, 0],
        [0, 6, 5],
    ],
    [
        [3, 1, 4],
        [0, 1, 1]
    ]
])

In [15]:
c

array([[[2, 1, 0],
        [0, 6, 5]],

       [[3, 1, 4],
        [0, 1, 1]]])

In [17]:
c.ndim

3

In [18]:
c.size

12

# Indexing and Slicing

In [20]:
A = np.array([
#.   0. 1. 2
    [2, 2, 3], # 0
    [5, 5, 5], # 1
    [6, 9, 0]  # 2
])

In [21]:
A[1][0]

5

In [23]:
A[0:3]

array([[2, 2, 3],
       [5, 5, 5],
       [6, 9, 0]])

In [24]:
A[:3, :3]

array([[2, 2, 3],
       [5, 5, 5],
       [6, 9, 0]])

# statistics

In [25]:
a = np.array([1, 2, 3, 4])

In [26]:
a.sum()

10

In [27]:
a.std()

1.118033988749895

In [28]:
a.var()

1.25

# Broadcasting and Vectorized operations

In [29]:
a = np.arange(4)

In [30]:
a

array([0, 1, 2, 3])

In [31]:
a+10

array([10, 11, 12, 13])

In [32]:
a*10

array([ 0, 10, 20, 30])

In [34]:
a+=2

In [35]:
a

array([4, 5, 6, 7])

In [36]:
b = np.array([1, 2, 3, 4])

In [37]:
a*b

array([ 4, 10, 18, 28])

In [38]:
a+b

array([ 5,  7,  9, 11])

# Boolean arrays

In [39]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [40]:
a[0], a[2]

(0, 2)

In [41]:
a[[True, True, False, True]]

array([0, 1, 3])

In [42]:
a

array([0, 1, 2, 3])

In [43]:
a>5

array([False, False, False, False])

In [44]:
a<2

array([ True,  True, False, False])

# Linear Algebra

In [45]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [46]:
A.dot(B)


array([[20, 14],
       [56, 41],
       [92, 68]])

In [47]:
A@B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [48]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# Size of objects

In [49]:
sys.getsizeof(1)

28

In [50]:
sys.getsizeof(10**100)

72

In [51]:
np.dtype(int).itemsize

8

# Lists

In [52]:
sys.getsizeof([1])

80

In [53]:
np.array([1]).nbytes

8